events {}

http {
    server {
        listen 80;

        # Grafana accessible sur /grafana/
        location /grafana/ {
            proxy_pass http://grafana:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Prometheus accessible sur /prometheus/
        # En production : restreindre l'accès par IP
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_set_header Host $host;
        }
    }
}